// Copyright (c) {year} Exphadis. All rights reserved.

namespace Exphadis.Core.Contract.Mapper;

public class PaymentProfile : Profile
{
    public PaymentProfile()
    {
        this.CreateMap<PromotionType, PromotionTypeDto>()
            ?.ReverseMap();

        this.CreateMap<ArrearConfiguration, ArrearConfigurationDto>()
            ?.ForMember(dest => dest.Month, opt => opt?.MapFrom(src => src.Month))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => src.Year))
            ?.ForMember(dest => dest.Date, opt => opt?.MapFrom(src => src.Date))
            ?.ForMember(dest => dest.Amount, opt => opt?.MapFrom(src => src.Amount))
            ?.ForMember(dest => dest.PeriodicityType, opt => opt?.MapFrom(src => src.IdPeriodicityType))
            ?.ForMember(dest => dest.MoneyMovementType, opt => opt?.MapFrom(src => src.IdMoneyMovementType));

        this.CreateMap<PaymentCommitment, PaymentCommitmentDto>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.IdStudent, opt => opt?.MapFrom(src => src.IdStudent))
            ?.ForMember(dest => dest.IdMoneyMovement, opt => opt?.MapFrom(src => (MoneyMovementTypeEnum)src.IdMoneyMovementType))
            ?.ForMember(dest => dest.Month, opt => opt?.MapFrom(src => (MonthEnum)src.Month))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => src.Year))
            ?.ForMember(dest => dest.IdStatus, opt => opt?.MapFrom(src => (CommitmentStatusEnum)src.IdPaymentCommitmentStatus))
            ?.ForMember(dest => dest.Date, opt => opt?.MapFrom(src => src.DateCommitment))
            ?.ForMember(dest => dest.IdPayment, opt => opt?.MapFrom(src => src.IdStudentPayment))
            ?.ForMember(dest => dest.Amount, opt => opt?.MapFrom(src => src.Amount))
            ?.ForMember(dest => dest.Comment, opt => opt?.MapFrom(src => src.Comment))
            ?.ForMember(dest => dest.StudentName, opt => opt?.MapFrom(src => $"{src.Student.Person.CompleteName}"))
            ?.ForMember(dest => dest.MoneyMovement, opt => opt?.MapFrom(src => $"{((MoneyMovementTypeEnum)src.IdMoneyMovementType).GetEnumMemberValue()}"))
            ?.ForMember(dest => dest.MonthValue, opt => opt?.MapFrom(src => $"{((MonthEnum)src.Month).GetEnumMemberValue()}"))
            ?.ForMember(dest => dest.HavePayment, opt => opt?.MapFrom(src => $"{(src.IdStudentPayment == 0 ? "NO" : "SI")}"))
            ?.ForMember(dest => dest.StatusValue, opt => opt?.MapFrom(src => $"{((CommitmentStatusEnum)src.IdPaymentCommitmentStatus).GetEnumMemberValue()}"))
            ?.ForMember(dest => dest.UserRegister, opt => opt?.MapFrom(src => src.UserRegister))
            ?.ForMember(dest => dest.TimeRegister, opt => opt?.MapFrom(src => src.TimeRegister));

        this.CreateMap<PaymentCommitmentDto, PaymentCommitment>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.IdEnrollment, opt => opt?.Ignore())
            ?.ForMember(dest => dest.IdStudent, opt => opt?.MapFrom(src => src.IdStudent))
            ?.ForMember(dest => dest.IdMoneyMovementType, opt => opt?.MapFrom(src => (int)src.IdMoneyMovement))
            ?.ForMember(dest => dest.DateCommitment, opt => opt?.MapFrom(src => src.Date))
            ?.ForMember(dest => dest.Month, opt => opt?.MapFrom(src => (int)src.Month))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => src.Year))
            ?.ForMember(dest => dest.IdPaymentCommitmentStatus, opt => opt?.MapFrom(src => (int)src.IdStatus))
            ?.ForMember(dest => dest.IdStudentPayment, opt => opt?.MapFrom(src => src.IdPayment))
            ?.ForMember(dest => dest.Amount, opt => opt?.MapFrom(src => src.Amount))
            ?.ForMember(dest => dest.Comment, opt => opt?.MapFrom(src => src.Comment))
            ?.ForMember(dest => dest.UserRegister, opt => opt?.MapFrom(src => src.UserRegister))
            ?.ForMember(dest => dest.TimeRegister, opt => opt?.MapFrom(src => src.TimeRegister))
            ?.ForMember(dest => dest.UserUpdated, opt => opt?.MapFrom(src => src.UserUpdated))
            ?.ForMember(dest => dest.TimeUpdated, opt => opt?.MapFrom(src => src.TimeUpdated))
            ?.ForMember(dest => dest.Student, opt => opt?.Ignore())
            ?.ForMember(dest => dest.Enrollment, opt => opt?.Ignore())
            ?.ForMember(dest => dest.StudentPayment, opt => opt?.Ignore())
            ?.ForMember(dest => dest.MoneyMovementType, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PaymentCommitmentStatus, opt => opt?.Ignore());

        this.CreateMap<MoneyMovementIngressNoTable, MoneyMovementReportDto>()
            ?.ForMember(dest => dest.IncomeMoneyMovementTypeEnum, opt => opt?.MapFrom(src => (MoneyMovementTypeEnum)src.PaymentTypeId))
            ?.ForMember(dest => dest.IdStudent, opt => opt?.MapFrom(src => src.StudentId))
            ?.ForMember(dest => dest.IdEnrollment, opt => opt?.MapFrom(src => src.EnrollmentId))
            ?.ForMember(dest => dest.UrlValidate, opt => opt?.MapFrom(src => $"{Constant.UrlValidate}/api/payment/{src.IdStudentPayment}/validate"))
            ?.ForMember(dest => dest.UrlInvoice, opt => opt?.MapFrom(src => $"{Constant.UrlValidate}/api/payment/{src.IdStudentPayment}/invoice"))
            ?.ForMember(dest => dest.PaymentDate, opt => opt?.MapFrom(src => src.PaymentDate))
            ?.ForMember(dest => dest.OperationNumber, opt => opt?.MapFrom(src => src.OperationNumber))
            ?.ForMember(dest => dest.Amount, opt => opt?.MapFrom(src => src.Amount))
            ?.ForMember(dest => dest.AmountShouldPay, opt => opt?.MapFrom(src => src.AmountShouldPay))
            ?.ForMember(dest => dest.StudentCompleteName, opt => opt?.MapFrom(src => src.Student))
            ?.ForMember(dest => dest.AttorneyCompleteName, opt => opt?.MapFrom(src => src.Attorney))
            ?.ForMember(dest => dest.Document, opt => opt?.MapFrom(src => src.Document))
            ?.ForMember(dest => dest.PaymentMethod, opt => opt?.MapFrom(src => src.PaymentMethod))
            ?.ForMember(dest => dest.PaymentType, opt => opt?.MapFrom(src => src.PaymentType))
            ?.ForMember(dest => dest.Level, opt => opt?.MapFrom(src => src.Level))
            ?.ForMember(dest => dest.Grade, opt => opt?.MapFrom(src => src.Grade))
            ?.ForMember(dest => dest.Month, opt => opt?.MapFrom(src => src.Month))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => src.Year))
            ?.ForMember(dest => dest.PersonRegister, opt => opt?.MapFrom(src => src.PersonRegister))
            ?.ForMember(dest => dest.Validated, opt => opt?.MapFrom(src => src.Validated))
            ?.ForMember(dest => dest.HaveInvoice, opt => opt?.MapFrom(src => src.HaveInvoice))
            ?.ForMember(dest => dest.BankType, opt => opt?.MapFrom(src => src.BankType))
            ?.ForMember(dest => dest.Comment, opt => opt?.MapFrom(src => src.Comment))
            ?.ForMember(dest => dest.Invoice, opt => opt?.MapFrom(src => src.Invoice));

        this.CreateMap<StudentPaymentPlan, StudentPaymentPlanDto>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.IdLevel, opt => opt?.MapFrom(src => src.IdLevel))
            ?.ForMember(dest => dest.LevelType, opt => opt?.MapFrom(src => $"{src.Level.Name}"))
            ?.ForMember(dest => dest.Pension, opt => opt?.MapFrom(src => src.Pension))
            ?.ForMember(dest => dest.Enrollment, opt => opt?.MapFrom(src => src.EnrollmentAmount))
            ?.ForMember(dest => dest.Material, opt => opt?.MapFrom(src => src.Material))
            ?.ForMember(dest => dest.Interest, opt => opt?.MapFrom(src => src.Interest))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => src.Year))
            ?.ForMember(dest => dest.PensionDay, opt => opt?.MapFrom(src => src.PensionDay))
            ?.ForMember(dest => dest.Interest, opt => opt?.MapFrom(src => src.Interest))
            ?.ForMember(dest => dest.Active, opt => opt?.MapFrom(src => src.Active))
            ?.ForMember(dest => dest.UserRegister, opt => opt?.MapFrom(src => src.UserRegister))
            ?.ForMember(dest => dest.TimeRegister, opt => opt?.MapFrom(src => src.TimeRegister))
            ?.ReverseMap();

        this.CreateMap<StudentPromotion, StudentPromotionDto>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.IdPromotion, opt => opt?.MapFrom(src => src.IdPromotion))
            ?.ForMember(dest => dest.IdStudent, opt => opt?.MapFrom(src => src.IdStudent))
            ?.ForMember(dest => dest.StudentName, opt => opt?.MapFrom(src => $"{src.Student.Person.CompleteName}"))
            ?.ForMember(dest => dest.PromotionType, opt => opt?.MapFrom(src => $"{src.PromotionType.Name}"))
            ?.ForMember(dest => dest.IdStudent, opt => opt?.MapFrom(src => src.IdStudent))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => src.Year));

        this.CreateMap<StudentPromotionDto, StudentPromotion>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.IdPromotion, opt => opt?.MapFrom(src => src.IdPromotion))
            ?.ForMember(dest => dest.IdEnrollment, opt => opt?.MapFrom(src => src.IdEnrollment))
            ?.ForMember(dest => dest.IdStudent, opt => opt?.MapFrom(src => src.IdStudent))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => src.Year))
            ?.ForMember(dest => dest.StudentName, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PromotionType, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PromotionName, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PromotionTypeValue, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PromotionValue, opt => opt?.Ignore())
            ?.ForMember(dest => dest.Student, opt => opt?.Ignore());

        this.CreateMap<WorkerPayment, WorkerPaymentDto>()
            ?.ReverseMap();

        this.CreateMap<WorkerDiscount, WorkerDiscountDto>()
            ?.ReverseMap();

        this.CreateMap<LoadBankPayment, LoadBankPaymentDto>()
            ?.ReverseMap();

        this.CreateMap<IncomeAndExpensesDto, IncomeAndExpenses>()
            ?.ReverseMap();

        this.CreateMap<StudentPayment, StudentPaymentDto>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.IdStudent, opt => opt?.MapFrom(src => src.IdStudent))
            ?.ForMember(dest => dest.Amount, opt => opt?.MapFrom(src => src.Amount))
            ?.ForMember(dest => dest.IdPaymentMethod, opt => opt?.MapFrom(src => src.IdPaymentMethod))
            ?.ForMember(dest => dest.Detail, opt => opt?.MapFrom(src => src.Detail))
            ?.ForMember(dest => dest.Month, opt => opt?.MapFrom(src => src.Month))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => src.Year))
            ?.ForMember(dest => dest.IncomeMoneyMovementTypeEnum, opt => opt?.MapFrom(src => src.IdMoneyMovementType))
            ?.ForMember(dest => dest.IdAttorney, opt => opt?.MapFrom(src => src.IdAttorney))
            ?.ForMember(dest => dest.Completed, opt => opt?.MapFrom(src => src.Completed))
            ?.ForMember(dest => dest.PaymentRelatedInformation, opt => opt?.MapFrom(src => src.PaymentRelated))
            ?.ForMember(dest => dest.IdIncomeExpense, opt => opt?.MapFrom(src => src.IdIncomeExpense))
            ?.ForMember(dest => dest.Validated, opt => opt?.MapFrom(src => src.Validated))
            ?.ForMember(dest => dest.Invoice, opt => opt?.MapFrom(src => src.Invoice))
            ?.ForMember(dest => dest.TicketUrl, opt => opt?.MapFrom(src => src.TicketUrl))
            ?.ForMember(dest => dest.ShouldBeTaken, opt => opt?.MapFrom(src => src.ShouldBeTaken))
            ?.ForMember(dest => dest.PaymentDate, opt => opt?.MapFrom(src => src.PaymentDate))
            ?.ForMember(dest => dest.Correlative, opt => opt?.MapFrom(src => src.Correlative))
            ?.ForMember(dest => dest.Message, opt => opt?.MapFrom(src => src.Message))
            ?.ForMember(dest => dest.Student, opt => opt?.MapFrom(src => src.Student))
            ?.ForMember(dest => dest.IncomeAndExpenses, opt => opt?.MapFrom(src => src.IncomeAndExpenses))
            ?.ForMember(dest => dest.PaymentType, opt => opt?.MapFrom(src => src.PaymentType))
            ?.ForMember(dest => dest.MoneyMovementType, opt => opt?.MapFrom(src => src.MoneyMovementType))
            ?.ForMember(dest => dest.Attorney, opt => opt?.MapFrom(src => src.Attorney))
            ?.ForMember(dest => dest.BankPayment, opt => opt?.MapFrom(src => src.BankPayment))
            ?.ForMember(dest => dest.ArrearsAmount, opt => opt?.Ignore())
            ?.ForMember(dest => dest.Commitment, opt => opt?.Ignore())
            ?.ForMember(dest => dest.IdSection, opt => opt?.Ignore())
            ?.ForMember(dest => dest.IdLevel, opt => opt?.Ignore())
            ?.ForMember(dest => dest.IdGrade, opt => opt?.Ignore())
            ?.ForMember(dest => dest.IdPerson, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PensionDay, opt => opt?.Ignore())
            ?.ForMember(dest => dest.CompletedArrears, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PaymentsRelated, opt => opt?.Ignore())
            ?.ForMember(dest => dest.IdStudentPayment, opt => opt?.Ignore())
            ?.ForMember(dest => dest.DetailPresentation, opt => opt?.Ignore())
            ?.ForMember(dest => dest.CompleteValue, opt => opt?.Ignore())
            ?.ForMember(dest => dest.TicketValue, opt => opt?.Ignore())
            ?.ForMember(dest => dest.NumberLinkedPayment, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PensionAmountByStudent, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PendingAmount, opt => opt?.MapFrom(src => src.PendingAmount))
            ?.ForMember(dest => dest.IdBankPayment, opt => opt?.MapFrom(src => src.IdBankPayment))
            ?.ForMember(dest => dest.CompleteName, opt => opt?.MapFrom(src => src.CompleteName))
            ?.ForMember(dest => dest.DocumentAttorney, opt => opt?.MapFrom(src => src.DocumentAttorney))
            ?.ForMember(dest => dest.PaymentRelatedInformation, opt => opt?.MapFrom(src => src.PaymentRelatedInformation))
            ?.ForMember(dest => dest.PaymentMethod, opt => opt?.MapFrom(src => src.PaymentMethod))
            ?.ForMember(dest => dest.MoneyMovement, opt => opt?.MapFrom(src => src.MoneyMovement));

        this.CreateMap<StudentPaymentDto, StudentPayment>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.IdStudent, opt => opt?.MapFrom(src => src.IdStudent))
            ?.ForMember(dest => dest.Amount, opt => opt?.MapFrom(src => src.Amount))
            ?.ForMember(dest => dest.IdPaymentMethod, opt => opt?.MapFrom(src => src.IdPaymentMethod))
            ?.ForMember(dest => dest.Detail, opt => opt?.MapFrom(src => src.Detail))
            ?.ForMember(dest => dest.Month, opt => opt?.MapFrom(src => src.Month))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => src.Year))
            ?.ForMember(dest => dest.IdMoneyMovementType, opt => opt?.MapFrom(src => $"{(int)src.IncomeMoneyMovementTypeEnum}"))
            ?.ForMember(dest => dest.IdAttorney, opt => opt?.MapFrom(src => src.IdAttorney))
            ?.ForMember(dest => dest.Completed, opt => opt?.MapFrom(src => src.Completed))
            ?.ForMember(dest => dest.PaymentRelated, opt => opt?.MapFrom(src => src.PaymentRelatedInformation))
            ?.ForMember(dest => dest.IdIncomeExpense, opt => opt?.MapFrom(src => src.IdIncomeExpense))
            ?.ForMember(dest => dest.Validated, opt => opt?.MapFrom(src => src.Validated))
            ?.ForMember(dest => dest.Invoice, opt => opt?.MapFrom(src => src.Invoice))
            ?.ForMember(dest => dest.TicketUrl, opt => opt?.MapFrom(src => src.TicketUrl))
            ?.ForMember(dest => dest.ShouldBeTaken, opt => opt?.MapFrom(src => src.ShouldBeTaken))
            ?.ForMember(dest => dest.PaymentDate, opt => opt?.MapFrom(src => src.PaymentDate))
            ?.ForMember(dest => dest.Correlative, opt => opt?.MapFrom(src => src.Correlative))
            ?.ForMember(dest => dest.Message, opt => opt?.MapFrom(src => src.Message))
            ?.ForMember(dest => dest.Student, opt => opt?.MapFrom(src => src.Student))
            ?.ForMember(dest => dest.IncomeAndExpenses, opt => opt?.MapFrom(src => src.IncomeAndExpenses))
            ?.ForMember(dest => dest.PaymentType, opt => opt?.MapFrom(src => src.PaymentType))
            ?.ForMember(dest => dest.MoneyMovementType, opt => opt?.MapFrom(src => src.MoneyMovementType))
            ?.ForMember(dest => dest.Attorney, opt => opt?.MapFrom(src => src.Attorney))
            ?.ForMember(dest => dest.BankPayment, opt => opt?.MapFrom(src => src.BankPayment))
            ?.ForMember(dest => dest.PendingAmount, opt => opt?.MapFrom(src => src.PendingAmount))
            ?.ForMember(dest => dest.IdBankPayment, opt => opt?.MapFrom(src => src.IdBankPayment))
            ?.ForMember(dest => dest.IsParent, opt => opt?.Ignore())
            ?.ForMember(dest => dest.CompleteName, opt => opt?.MapFrom(src => src.CompleteName))
            ?.ForMember(dest => dest.DocumentAttorney, opt => opt?.MapFrom(src => src.DocumentAttorney))
            ?.ForMember(dest => dest.PaymentRelatedInformation, opt => opt?.MapFrom(src => src.PaymentRelatedInformation))
            ?.ForMember(dest => dest.PaymentMethod, opt => opt?.MapFrom(src => src.PaymentMethod))
            ?.ForMember(dest => dest.MoneyMovement, opt => opt?.MapFrom(src => src.MoneyMovement));

        this.CreateMap<StudentPaymentNoTable, StudentPaymentDto>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.IdStudent, opt => opt?.MapFrom(src => src.IdStudent))
            ?.ForMember(dest => dest.PendingAmount, opt => opt?.MapFrom(src => src.PendingAmount))
            ?.ForMember(dest => dest.Amount, opt => opt?.MapFrom(src => src.Amount))
            ?.ForMember(dest => dest.CompleteName, opt => opt?.MapFrom(src => src.CompleteName))
            ?.ForMember(dest => dest.IdPaymentMethod, opt => opt?.MapFrom(src => src.IdPaymentMethod))
            ?.ForMember(dest => dest.IncomeMoneyMovementTypeEnum, opt => opt?.MapFrom(src => src.IdMoneyMovementType))
            ?.ForMember(dest => dest.IdAttorney, opt => opt?.MapFrom(src => src.IdAttorney))
            ?.ForMember(dest => dest.MoneyMovement, opt => opt?.MapFrom(src => src.MoneyMovement))
            ?.ForMember(dest => dest.PaymentMethod, opt => opt?.MapFrom(src => src.PaymentMethod))
            ?.ForMember(dest => dest.Detail, opt => opt?.MapFrom(src => src.Detail))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => src.Year))
            ?.ForMember(dest => dest.Month, opt => opt?.MapFrom(src => src.Month))
            ?.ForMember(dest => dest.IdIncomeExpense, opt => opt?.MapFrom(src => src.IdIncomeExpense))
            ?.ForMember(dest => dest.IdStudentPayment, opt => opt?.MapFrom(src => src.IdStudentPayment))
            ?.ForMember(dest => dest.IdBankPayment, opt => opt?.MapFrom(src => src.IdBankPayment ?? 0))
            ?.ForMember(dest => dest.DocumentAttorney, opt => opt?.MapFrom(src => src.DocumentAttorney))
            ?.ForMember(dest => dest.TicketUrl, opt => opt?.MapFrom(src => src.TicketUrl))
            ?.ForMember(dest => dest.UserRegister, opt => opt?.MapFrom(src => src.UserRegister))
            ?.ForMember(dest => dest.TimeRegister, opt => opt?.MapFrom(src => src.TimeRegister))
            ?.ForMember(dest => dest.DetailPresentation, opt => opt?.MapFrom(src => src.DetailPresentation))
            ?.ForMember(dest => dest.Completed, opt => opt?.MapFrom(src => src.Completed))
            ?.ForMember(dest => dest.ShouldBeTaken, opt => opt?.MapFrom(src => src.ShouldBeTaken))
            ?.ForMember(dest => dest.PaymentRelatedInformation, opt => opt?.MapFrom(src => src.PaymentRelated))
            ?.ForMember(dest => dest.CompleteValue, opt => opt?.MapFrom(src => src.CompleteValue))
            ?.ForMember(dest => dest.TicketValue, opt => opt?.MapFrom(src => src.TicketValue))
            ?.ForMember(dest => dest.NumberLinkedPayment, opt => opt?.MapFrom(src => src.NumberLinkedPayment))
            ?.ForMember(dest => dest.PaymentsRelated, opt => opt?.MapFrom(src => src.PaymentRelatedList))
            ?.ForMember(dest => dest.PaymentRelatedInformation, opt => opt?.MapFrom(src => src.PaymentRelatedInformation))
            ?.ForMember(dest => dest.PaymentDate, opt => opt?.MapFrom(src => src.PaymentDate))
            ?.ForMember(dest => dest.Correlative, opt => opt?.MapFrom(src => src.Correlative))
            ?.ForMember(dest => dest.Invoice, opt => opt?.MapFrom(src => src.Invoice))
            ?.ForMember(dest => dest.Validated, opt => opt?.MapFrom(src => src.Validated))
            ?.ForMember(dest => dest.IdLevel, opt => opt?.MapFrom(src => src.IdLevel))
            ?.ForMember(dest => dest.IdGrade, opt => opt?.MapFrom(src => src.IdGrade))
            ?.ForMember(dest => dest.PensionAmountByStudent, opt => opt?.MapFrom(src => src.PensionAmountByStudent));

        this.CreateMap<BankPayment, BankPaymentDto>()
            ?.ReverseMap();

        this.CreateMap<PaymentPendingShowDto, PaymentPendingShow>()
            ?.ReverseMap();

        this.CreateMap<PaymentFoundedByOperationNumberDto, PaymentFoundedByOperationNumber>()
            ?.ReverseMap();

        this.CreateMap<Egress, EgressDto>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.EgressTypeId, opt => opt?.MapFrom(src => $"{(MoneyMovementTypeEnum)src.EgressTypeId}"))
            ?.ForMember(dest => dest.PettyCashTypeId, opt => opt?.MapFrom(src => $"{src.PettyCashType.TryParseEnum<PettyCashTypeEnum>()}"))
            ?.ForMember(dest => dest.PaymentMethodId, opt => opt?.MapFrom(src => $"{(PaymentMethodTypeEnum)src.PaymentMethodId}"))
            ?.ForMember(dest => dest.Month, opt => opt?.MapFrom(src => src.Month))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => src.Year))
            ?.ForMember(dest => dest.PersonRegisterId, opt => opt?.MapFrom(src => src.PersonRegisterId))
            ?.ForMember(dest => dest.PersonWorkerId, opt => opt?.MapFrom(src => src.PersonWorkerId))
            ?.ForMember(dest => dest.Amount, opt => opt?.MapFrom(src => src.Amount))
            ?.ForMember(dest => dest.PaymentDate, opt => opt?.MapFrom(src => src.PaymentDate))
            ?.ForMember(dest => dest.OperationNumber, opt => opt?.MapFrom(src => src.OperationNumber))
            ?.ForMember(dest => dest.ImageUrl, opt => opt?.MapFrom(src => src.ImageUrl))
            ?.ForMember(dest => dest.Comments, opt => opt?.MapFrom(src => src.Comments))
            ?.ForMember(dest => dest.IncomeAndExpenseId, opt => opt?.MapFrom(src => src.IncomeAndExpenseId))
            ?.ForMember(dest => dest.PersonRegister, opt => opt?.MapFrom(src => src.PersonRegister))
            ?.ForMember(dest => dest.Information, opt => opt?.MapFrom(src => $"({((MoneyMovementTypeEnum)src.EgressTypeId).GetEnumMemberValue()}) {((PaymentMethodTypeEnum)src.PaymentMethodId).GetEnumMemberValue()} - S/.{src.Amount:F2} el '{src.PaymentDate:dd/MM/yyyy}' [COD. '{src.OperationNumber}]'"))
            ?.ForMember(dest => dest.EgressType, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PettyCashType, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PaymentMethod, opt => opt?.Ignore());

        this.CreateMap<EgressDto, Egress>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.PettyCashType, opt => opt?.MapFrom(src => $"{src.PettyCashTypeId.GetEnumMemberValue()}"))
            ?.ForMember(dest => dest.IncomeAndExpenseId, opt => opt?.MapFrom(src => src.IncomeAndExpenseId))
            ?.ForMember(dest => dest.EgressTypeId, opt => opt?.MapFrom(src => $"{(int)src.EgressTypeId}"))
            ?.ForMember(dest => dest.PaymentMethodId, opt => opt?.MapFrom(src => $"{(int)src.PaymentMethodId}"))
            ?.ForMember(dest => dest.Month, opt => opt?.MapFrom(src => $"{src.PaymentDate.Month}"))
            ?.ForMember(dest => dest.Year, opt => opt?.MapFrom(src => $"{src.PaymentDate.Year}"))
            ?.ForMember(dest => dest.PersonRegisterId, opt => opt?.MapFrom(src => src.PersonRegisterId))
            ?.ForMember(dest => dest.PersonWorkerId, opt => opt?.MapFrom(src => src.PersonWorkerId))
            ?.ForMember(dest => dest.Amount, opt => opt?.MapFrom(src => src.Amount))
            ?.ForMember(dest => dest.PaymentDate, opt => opt?.MapFrom(src => src.PaymentDate))
            ?.ForMember(dest => dest.OperationNumber, opt => opt?.MapFrom(src => src.OperationNumber))
            ?.ForMember(dest => dest.ImageUrl, opt => opt?.MapFrom(src => src.ImageUrl))
            ?.ForMember(dest => dest.Comments, opt => opt?.MapFrom(src => src.Comments))
            ?.ForMember(dest => dest.IncomeAndExpenses, opt => opt?.Ignore())
            ?.ForMember(dest => dest.EgressType, opt => opt?.Ignore())
            ?.ForMember(dest => dest.PersonRegister, opt => opt?.Ignore());

        this.CreateMap<EgressInvoiceDto, EgressInvoice>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.Type, opt => opt?.MapFrom(src => $"{src.Type}"))
            ?.ForMember(dest => dest.SupplierId, opt => opt?.MapFrom(src => src.SupplierId))
            ?.ForMember(dest => dest.Amount, opt => opt?.MapFrom(src => src.Amount))
            ?.ForMember(dest => dest.Date, opt => opt?.MapFrom(src => src.Date))
            ?.ForMember(dest => dest.Code, opt => opt?.MapFrom(src => src.Code))
            ?.ForMember(dest => dest.PersonRegisterId, opt => opt?.MapFrom(src => src.PersonRegisterId))
            ?.ForMember(dest => dest.EgressIds, opt => opt?.MapFrom(src => $"{src.EgressIds.ToList().ConvertToIntListString()}"))
            ?.ForMember(dest => dest.AttachmentUrl, opt => opt?.MapFrom(src => src.AttachmentUrl))
            ?.ForMember(dest => dest.Comments, opt => opt?.MapFrom(src => src.Comments));

        this.CreateMap<EgressInvoice, EgressInvoiceDto>()
            ?.ForMember(dest => dest.Id, opt => opt?.MapFrom(src => src.Id))
            ?.ForMember(dest => dest.Type, opt => opt.MapFrom(src => $"{src.Type.TryParseEnum<EgressInvoiceTypeEnum>()}"))
            ?.ForMember(dest => dest.SupplierId, opt => opt?.MapFrom(src => src.SupplierId))
            ?.ForMember(dest => dest.Amount, opt => opt?.MapFrom(src => src.Amount))
            ?.ForMember(dest => dest.Date, opt => opt?.MapFrom(src => src.Date))
            ?.ForMember(dest => dest.Code, opt => opt?.MapFrom(src => src.Code))
            ?.ForMember(dest => dest.PersonRegisterId, opt => opt?.MapFrom(src => src.PersonRegisterId))
            ?.ForMember(dest => dest.EgressIds, opt => opt?.Ignore())
            ?.ForMember(dest => dest.AttachmentUrl, opt => opt?.MapFrom(src => src.AttachmentUrl))
            ?.ForMember(dest => dest.Comments, opt => opt?.MapFrom(src => src.Comments))
            ?.ForMember(dest => dest.Supplier, opt => opt?.MapFrom(src => src.Supplier));
    }
}
